all:
	#gcc -o myLib myLib.c -Wall
	#gcc -c -fpic myLib.c -Wall -Werror
	#gcc -shared -o lfsreader.so myLib.o
	
	gcc -o lfsreader myLib.c -Wall
	
	#gcc -c myLib.c -o myLib.o
	#ar rcs lfsreader myLib.o

clean:
	rm -f myLib
	rm -f lfsreader
